# Site identity
title: "Bias in GLAM: From Data Creation to Algorithmic Access"
description: ""
url: "https://BiasInGLAM.github.io"
baseurl: ""

# Theme
theme: minima
#remote_theme: "mmistakes/minimal-mistakes@4.26.2"
#plugins:
#  - jekyll-remote-theme
# theme: jekyll-theme-minimal  # check for other supported themes later

# Optional but useful in basic design
show_downloads: false

# Items included in the menu bar (and their order)
header_pages:
  - cfp.md
  - program.md
  - organizers.md
